version: '3'

services:
  todofront:
    image: todofrontend
    # build: ./todo-app/front-end/
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: on-failure

  todotests:
    image: todotests
    restart: on-failure
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
